### ISSUE TITLE
Logic of the allocation

### ISSUE THREAD

**Issue by mathiasbrenner** [AndresCL/sherpany_demo#2]
Validation of a document with the name "2_xxx.pdf" also allocations within agenda item 5.2 etc.
See http://recordit.co/ETYcAVKada

**Comment by AndresCL** [comment]
I have updated the code to handle this cases. 

This is comparing entire filename and entire agenda title, and dividing this strings in chunks for better comparison.

So this case, 5.2 matches a file called 2_something so now when comparing string chunks for agenda title and document file names, if 5.2 is found, its treated as float and compared only with number part so 5.2 != 2 and for that it will not be assigned.

![captura de pantalla 2017-03-08 a las 12 09 31](https://cloud.githubusercontent.com/assets/1790792/23709418/1e3bce3e-03f8-11e7-80c0-07dd05151370.png)

**Comment by mathiasbrenner** [comment]
"Admin.pdf" could be allocated to the first agenda item in my example. It should, right?

**Comment by AndresCL** [comment]
Yes, this is being allocated to first one. Look.

![captura de pantalla 2017-03-10 a las 12 11 00](https://cloud.githubusercontent.com/assets/1790792/23800319/ae406de4-058a-11e7-9e04-223361b002b5.png)
